package in.sanskar.tempotrack.ui

data class TempoTrackStrings(
    val appName: String,
    val tagline: String,
    val credit: String,
    val stopwatch: String,
    val history: String,
    val settings: String,
    val about: String,
    val start: String,
    val pause: String,
    val resume: String,
    val reset: String,
    val lap: String,
    val startTiming: String,
    val onboardingValue: String,
    val onboardingPrivacy: String,
    val sessionName: String,
    val sessionNameHint: String,
    val saveSession: String,
    val saveFailed: String,
    val recordLapHint: String,
    val fastest: String,
    val average: String,
    val slowest: String,
    val recorded: String,
    val searchSessions: String,
    val historyReadFailed: String,
    val exportJson: String,
    val exportCsv: String,
    val exportFailed: String,
    val restoreFailed: String,
    val noSavedSessions: String,
    val noMatchingSessions: String,
    val delete: String,
    val deleteFailed: String,
    val appearance: String,
    val accessibility: String,
    val system: String,
    val light: String,
    val dark: String,
    val largeControls: String,
    val largeControlsDescription: String,
    val reducedMotion: String,
    val reducedMotionDescription: String,
    val desktop: String,
    val floatingStopwatch: String,
    val floatingStopwatchDescription: String,
    val privacy: String,
    val privacyDescription: String,
    val data: String,
    val dataDescription: String,
    val updates: String,
    val updatesDescription: String,
    val openSourceCredit: String,
    val license: String,
    val github: String,
    val buyMeACoffee: String,
    val businessPrimary: String,
    val businessSecondary: String,
    val support: String,
    val localDataDescription: String,
)

val EnglishTempoTrackStrings = TempoTrackStrings(
    appName = "TempoTrack",
    tagline = "Precise timing. Local-first history. Portable data.",
    credit = "Made by the Sanskar",
    stopwatch = "Stopwatch",
    history = "History",
    settings = "Settings",
    about = "About",
    start = "Start",
    pause = "Pause",
    resume = "Resume",
    reset = "Reset",
    lap = "Lap",
    startTiming = "Start timing",
    onboardingValue = "A precise, privacy-first stopwatch with laps, searchable local history and portable exports.",
    onboardingPrivacy = "Your sessions stay on this device unless you explicitly export them.",
    sessionName = "Session name",
    sessionNameHint = "Optional; defaults to a timestamp-based name",
    saveSession = "Save session",
    saveFailed = "Could not save this session.",
    recordLapHint = "Record a lap while the stopwatch is running to compare splits.",
    fastest = "Fastest",
    average = "Average",
    slowest = "Slowest",
    recorded = "Recorded",
    searchSessions = "Search sessions",
    historyReadFailed = "Could not read saved sessions.",
    exportJson = "Export JSON",
    exportCsv = "Export CSV",
    exportFailed = "Could not export this file.",
    restoreFailed = "Could not restore the deleted session.",
    noSavedSessions = "No saved sessions yet.",
    noMatchingSessions = "No sessions match your search.",
    delete = "Delete",
    deleteFailed = "Could not delete this session.",
    appearance = "Appearance",
    accessibility = "Accessibility",
    system = "System",
    light = "Light",
    dark = "Dark",
    largeControls = "Large controls",
    largeControlsDescription = "Increase primary touch target and timer sizes.",
    reducedMotion = "Reduced motion",
    reducedMotionDescription = "Prefer minimal motion where animations are used.",
    desktop = "Desktop",
    floatingStopwatch = "Floating mini stopwatch",
    floatingStopwatchDescription = "Show a compact always-on-top timer window.",
    privacy = "Privacy",
    privacyDescription = "TempoTrack does not require an account and does not transmit session data.",
    data = "Data",
    dataDescription = "Saved sessions and preferences use application-private local storage. Use History to export JSON backups or CSV data.",
    updates = "Updates",
    updatesDescription = "Release information is published at https://github.com/sanskarIN/tempotrack/releases",
    openSourceCredit = "Open-source MIT project • Made by the Sanskar",
    license = "License: MIT",
    github = "GitHub",
    buyMeACoffee = "Buy Me a Coffee",
    businessPrimary = "Business: sanskarin@outlook.in",
    businessSecondary = "Business: sanskarin.business@gmail.com",
    support = "Support: supportramsandesh@gmail.com",
    localDataDescription = "TempoTrack stores stopwatch sessions locally. Nothing is uploaded unless you choose to export and share a file.",
)
